Resolves #2070 Add new x-remote-addr var to the get_ip() function
mybb/mybb pull request #3400
Opened 2018-08-18 09:34 UTC by effone

Attempt to resolve #2070 

Task List:
- [x] Modify `get_ip( )` function to handle various headers
- [x] Cover CloudFlare IP override
- [ ] Add ACP Setting for users to select desired headers

@dvz  @euantorano (or some expert/s) please review the ordering in `$filter_headers` array. This is important as the first match will be considered to return.

2018-08-18 12:36 UTC, effone commented
The ACP settings will be created after review / confirmation of considered headers and their check sequence.

2018-09-17 15:04 UTC, skmedix requested changes

2018-09-17 15:04 UTC, skmedix commented on inc/functions.php
> +			'HTTP_CF_CONNECTING_IP ', // Cloudflare Proxy
Removed space from the end of string

2018-10-14 14:56 UTC, Eldenroot commented
@effone - will you finish this one? Thx

2019-05-29 17:42 UTC, Ben-MyBB commented
@effone Ping! Reminder about this PR :)

2019-05-29 18:31 UTC, effone commented
> The actual list for attempts could be included in the installation process
Failed to understand this part @dvz

2019-05-29 18:37 UTC, dvz commented
Fixed the link (https://community.mybb.com/thread-219338.html) - when the installer is rewritten, the header name can be detected automatically.

2025-12-05 19:24 UTC, Ben-MyBB commented
?

2025-12-15 03:27 UTC, Sama34 commented
If I understand this one correctly, the ACP settings are missing.

Please clarify if you are not adding a setting, so we are able to test properly.

2026-02-11 11:26 UTC, Ben-MyBB commented
Closed as the PR needs to be rewritten.

2026-02-11 11:26 UTC, closed without merging