Fixes #4023 Editing help document/section seems doesn't check input
mybb/mybb pull request #4028
Opened 2020-05-29 20:34 UTC by PaulBender

Fixes #4023

2020-06-02 17:18 UTC, Ben-MyBB commented
This works fine. What I did notice is that when updating the Help Documents in the ACP editor the changes aren't actually shown in the front end documents at all. I do recall reading something similiar. I'm going to have a search and I will update this comment.

2020-06-02 18:22 UTC, Ben-MyBB approved these changes

2020-06-05 07:17 UTC, yuliu requested changes
Looks good and it's worth noting that `$hid` is not defined if request method isn't POST in
https://github.com/mybb/mybb/blob/9feef312dc22abef36dcc1ddb1a703e66d9c2fe1/admin/modules/config/help_documents.php#L428
where `$hid` is defined in
https://github.com/mybb/mybb/blob/9feef312dc22abef36dcc1ddb1a703e66d9c2fe1/admin/modules/config/help_documents.php#L366

I do notice some occurrences like that somewhere else in AdminCP but only remember this one..

2020-06-06 18:31 UTC, PaulBender commented
That should fix it

2020-09-07 17:07 UTC, JordanMussi approved these changes

2020-09-07 17:08 UTC, merged