Resolves #2058/#1758 - Can view/reply only own threads and guests
mybb/mybb pull request #4072
Opened 2020-06-16 11:56 UTC by Ben-MyBB

This PR will remove the following options from the guest usergroup since they currently have no effect if they are either disabled or enabled.

Editing/Deleting Options
Can edit own posts?
Can delete own posts?
Can delete own threads?
Can update own attachments?

Resolves https://github.com/mybb/mybb/issues/2058 & Resolves https://github.com/mybb/mybb/issues/1758

2020-06-16 11:58 UTC, Ben-MyBB commented
Actually, the whole Editing/Deleting Options section can be removed with the other two options:
 Can view deletion notices?
Edit Time Limit
The number of minutes until regular users cannot edit their own posts (if they have the permission). Enter 0 (zero) for no limit.


I'll push the extra changes shortly.

2020-06-17 15:58 UTC, JordanMussi requested changes
These options are still available for the forum-management permission options:

https://github.com/mybb/mybb/blob/1326eea040ef2637ac58c92512f9b6f7dd7696bb/admin/modules/forum/management.php#L722-L726

Also need to work out what to do about `canonlyviewownthreads` as mentioned in #1758

2020-06-17 15:58 UTC, JordanMussi commented on admin/modules/user/groups.php
> +	{
```suggestion
	{
```

2020-06-17 15:58 UTC, JordanMussi commented on admin/modules/user/groups.php
> +	};
```suggestion
		);
		$form_container->output_row($lang->editing_deleting_options, "", "<div class=\"group_settings_bit\">".implode("</div><div class=\"group_settings_bit\">", $editing_options)."</div>");
	}
```

2020-06-17 18:22 UTC, Ben-MyBB commented
> 
> 
> These options are still available for the forum-management permission options:
> 
> https://github.com/mybb/mybb/blob/1326eea040ef2637ac58c92512f9b6f7dd7696bb/admin/modules/forum/management.php#L722-L726
> 
> Also need to work out what to do about `canonlyviewownthreads` as mentioned in #1758

Since those are in a different place, I wonder if we should treat them as a seperate issue or handle them here?

In terms of `canonlyviewownthreads` we could just check if you are editing group ID=1 and remove that option if so?

2020-06-17 18:28 UTC, JordanMussi commented
I think best to bundle as it’s basically the same setting just on the per forum basis.

That’s what I was thinking too. It might be worth doing a review to see what effects these options have at the moment and whether we should set them all to 0 on upgrade for guests...

2020-06-17 18:36 UTC, Ben-MyBB commented
I'll update this PR to fix both of those points raised. I think it's actually just a small inconsistency with the options being shown because there's no way to validate which guest has posted without using the questionable method of checking IP addresses but we obviously don't have that implemented.

2020-06-17 19:56 UTC, JordanMussi commented
Was thinking it might be worth a check to make sure everywhere is ensuring uid>0 before checking those settings but we can get to that a bit later.

2020-06-18 19:50 UTC, JordanMussi commented
> In terms of `canonlyviewownthreads` we could just check if you are editing group ID=1 and remove that option if so?

Please could you do this too then?

Also I think we should 0 out these options in the upgrade script since at the moment guests *can* see other guest's threads when `canonlyviewownthreads` is enabled (I'm sure the same is true for attachments...)

2020-06-19 09:43 UTC, Ben-MyBB commented
> > In terms of `canonlyviewownthreads` we could just check if you are editing group ID=1 and remove that option if so?
> 
> 
> 
> Please could you do this too then?
> 
> 
> 
> Also I think we should 0 out these options in the upgrade script since at the moment guests *can* see other guest's threads when `canonlyviewownthreads` is enabled (I'm sure the same is true for attachments...)

Yep, that option should be removed along with one other in my latest changes. (Hopefully github hasn’t removed them as well?) 

I can take a look at the upgrade script when I get on my laptop in a bit.

2020-06-19 12:12 UTC, JordanMussi commented
> Yep, that option should be removed along with one other in my latest changes. (Hopefully github hasn’t removed them as well?)

Quite right - I didn't see it sneak in there :wink:

2021-02-07 17:13 UTC, Eldenroot commented
@Ben-MyBB - please can you finish this one?

2021-04-06 14:12 UTC, Ben-MyBB commented
I will try and get this finished for .27.

2021-04-07 12:26 UTC, closed without merging