threadmode should be set empty to reflect admin default
mybb/mybb pull request #4102
Opened 2020-06-29 13:19 UTC by rajat315315

Closes #4085

This omitted code checks if the User Thread Mode is User Default (empty string) then sets it to Admin Default.
Now, this creates problem.
If Admin has set to "Threaded" or "Linear" it sets User Thread Mode instead of leaving the field unset.
Now, if admin re-changes the field, it will not change the User Thread Mode again as it is already been set.

2020-06-29 14:20 UTC, JordanMussi requested changes
Thanks for the PR!

I don't think we should be removing the check for a valid value since we still want the field to only be `''`, `'threaded'`, or `'linear'`. What do you think about the following?

```php
		if($this->method == "insert" || (isset($options['threadmode']) && $options['threadmode'] != "linear" && $options['threadmode'] != "threaded" && $options['threadmode'] != ''))
		{
			$options['threadmode'] = '';
		}
```

2020-06-29 19:09 UTC, rajat315315 commented
@JordanMussi Thanks for the help. Totally missed checking the input.

2020-07-02 20:19 UTC, JordanMussi commented on inc/datahandlers/user.php
> +		if($this->method == "insert" || (isset($options['threadmode']) && $options['threadmode'] != "linear" && $options['threadmode'] != "threaded" && $options['threadmode'] != ''))
```suggestion

		if($this->method == "insert" || (isset($options['threadmode']) && $options['threadmode'] != "linear" && $options['threadmode'] != "threaded" && $options['threadmode'] != ''))
```

2020-07-02 20:25 UTC, JordanMussi approved these changes

2020-07-02 20:28 UTC, merged

2020-07-02 20:28 UTC, JordanMussi commented
@rajat315315 thank you for your first contribution to be merged into MyBB! 😀