Fixes #4173 - Show 'edited by' Messages
mybb/mybb pull request #4174
Opened 2020-11-17 17:49 UTC by Eldenroot

Resolves #4173 

reported by @Supryk

2020-11-17 20:01 UTC, euantorano requested changes

2020-11-17 20:01 UTC, euantorano commented on inc/functions_post.php
> +		if($post['edituid'] != 0 && $post['edittime'] != 0 && $post['editusername'] != "" && (($mybb->settings['showeditedby'] != 0 && $usergroup['cancp'] == 0) || ($mybb->settings['showeditedbyadmin'] !=
This is a syntax error, specifically:

```
$usergroup['cancp'] == || is_moderator($post['fid'], "", $post['uid']))
```

I guess the below suggestion is correct but haven't tested the actual logic:

```suggestion
		if($post['edituid'] != 0 && $post['edittime'] != 0 && $post['editusername'] != "" && (($mybb->settings['showeditedby'] != 0 && $usergroup['cancp'] == 0) || ($mybb->settings['showeditedbyadmin'] != 0 && $usergroup['cancp'] == 1 || is_moderator($post['fid'], "", $post['uid'])))))
```

2020-11-17 20:07 UTC, Eldenroot commented
Ok, thx!

2020-11-18 00:09 UTC, Sama34 commented
Can you remove the `$usergroup['cancp'] == 0` check ?

As per the setting description;
> Show 'edited by' Messages
> Once a post is edited by a regular user, do you want to show the edited by message?

Why are users with ACP access excepted of this _supposed_ general setting? Hope my inquiry is clear. @euantorano

2020-11-18 18:25 UTC, Eldenroot commented
@Sama34 

```
Show 'edited by' Message for Administrators and Moderators
Do you want to show edited by messages for posts created by administrators and moderators?
```

2020-11-19 21:41 UTC, Eldenroot commented
@euantorano @Sama34 - OK, there is no issue to made the required change but please make a final decision :)

2020-11-19 22:03 UTC, Sama34 commented
I think I got confused. Instead, you should add the `is_moderator` check to the previous conditional as well. Like so:
`$mybb->settings['showeditedby'] != 0 && $usergroup['cancp'] == 0 && !is_moderator($post['fid'], "", $post['uid'])`

Ignore my previous inquiry.

2021-01-14 19:40 UTC, Eldenroot commented
@Sama34 @euantorano - so final decision? This should be fine :)

2021-02-07 16:30 UTC, merged

2021-05-17 16:37 UTC, dvz commented
The added condition should be related to `$mybb->settings['showeditedbyadmin'] != 0`, but may evaluate as true independently when `$mybb->settings['showeditedbyadmin'] != 0 && $usergroup['cancp'] == 1` evaluates as false (missing group parenthesis).
@Sama34's change is also needed - otherwise notices related to users without ACP access (`$usergroup['cancp'] == 0`), but with moderator permissions, will still be shown, even with `showeditedbyadmin` setting enabled.

2021-05-26 20:29 UTC, Sama34 commented
So the following might be the desired result:
```
if(
	$post['edituid'] != 0 && $post['edittime'] != 0 && $post['editusername'] != "" && (
		($mybb->settings['showeditedby'] != 0 && $usergroup['cancp'] == 0 && !is_moderator($post['fid'], "", $post['uid'])) ||
		($mybb->settings['showeditedbyadmin'] != 0 && (
			$usergroup['cancp'] == 1 || is_moderator($post['fid'], "", $post['uid'])
		))
	)
)
```

Modified for improved readability.