Fix #3804 Post Merge Verification
mybb/mybb pull request #4214
Opened 2020-12-30 12:56 UTC by Xazin

Due to missing check on whether a post is a merge before a post is validated, it was possible to double post and merge multiple images and videos despite the limitations imposed through settings in AdminCP (Post Settings).

Resolves #3804

2020-12-30 13:01 UTC, Xazin commented
The solution is rough but gives insight into a possible solution for issue #3804 .

2020-12-30 22:21 UTC, Xazin commented
I performed some tests but hope that someone can review the changes and see if there are any problems with the logic.

2021-01-07 22:03 UTC, Sama34 requested changes
https://github.com/mybb/mybb/issues/3804#issuecomment-752590036
> * if the limits are verified on the resulting posts, like currently proposed in #4214, it may be impossible to post more items within _Post Merge Time_, which may be unexpected.

Is this already accounted for in this current code? It doesn't seem like so to me.

2021-01-07 22:03 UTC, Sama34 commented on inc/datahandlers/post.php
> +				} else {
```suggestion
				}
				else
				{
```

2021-01-10 03:06 UTC, Xazin commented
> [#3804 (comment)](https://github.com/mybb/mybb/issues/3804#issuecomment-752590036)
> 
> > * if the limits are verified on the resulting posts, like currently proposed in #4214, it may be impossible to post more items within _Post Merge Time_, which may be unexpected.
> 
> Is this already accounted for in this current code? It doesn't seem like so to me.

Yes, this fixes the issues from #3804 and the issues @dvz mentioned on that issue regarding the original pr that was made.

2021-02-07 19:28 UTC, euantorano commented
This looks good to me and seems to work based on my testing.

2021-02-07 19:29 UTC, merged