Missing collation in upgrade script
mybb/mybb pull request #4362
Opened 2021-04-20 23:38 UTC by effone

Will make issue later ...

2021-04-21 11:21 UTC, euantorano requested changes

2021-04-21 11:21 UTC, euantorano commented on install/upgrade.php
> +		) ENGINE=MyISAM{$collation};");
Note, `ENGINE` is MySQL specific.

2021-05-10 20:25 UTC, Eldenroot commented
@effone - please, could you fix the PR?

2021-05-25 21:09 UTC, euantorano commented
Added some logic to check for MySQL/MySQLi before setting the engine.

2021-05-25 21:11 UTC, euantorano approved these changes

2021-05-25 21:11 UTC, merged