Ability to suspend private messaging ability
mybb/mybb pull request #4376
Opened 2021-05-22 12:14 UTC by Xazin

https://community.mybb.com/thread-195240.html

Based on the above-planned feature, the ability to suspend a user's private messaging abilities. If a user is suspended using private messaging, the user can neither send nor receive new private messages.

Options to moderate suspension of PM added both AdminCP and ModCP similar to suspend posts and moderate posts.

2021-05-22 12:19 UTC, Ben-MyBB commented
Great job
On 22 May 2021, 13:15 +0100, Mathias Mogensen ***@***.***>, wrote:
> https://community.mybb.com/thread-195240.html
> Based on the above-planned feature, the ability to suspend a user's private messaging abilities. If a user is suspended using private messaging, the user can neither send nor receive new private messages.
> Options to moderate suspension of PM added both AdminCP and ModCP similar to suspend posts and moderate posts.
> You can view, comment on, or merge this pull request online at:
> https://github.com/mybb/mybb/pull/4376
> Commit Summary
>
> • Update user_users.lang.php
> • Add columns to mybb_users table
> • Add Suspend PM to Moderate User
> • Restrict access to private for pm suspended users
> • Add pm suspension to user cleanup task
> • Restrict sending PMs to a pm suspended user
> • ModCP option to Suspend Private Messaging
> • Last fixes and implementations
>
> File Changes
>
> • M admin/modules/user/users.php (73)
> • M inc/datahandlers/pm.php (2)
> • M inc/languages/english/admin/user_users.lang.php (3)
> • M inc/languages/english/modcp.lang.php (5)
> • M inc/tasks/usercleanup.php (7)
> • M install/resources/mybb_theme.xml (99)
> • M install/resources/mysql_db_tables.php (2)
> • M install/resources/pgsql_db_tables.php (2)
> • M install/resources/sqlite_db_tables.php (2)
> • M modcp.php (40)
> • M private.php (2)
>
> Patch Links:
>
> • https://github.com/mybb/mybb/pull/4376.patch
> • https://github.com/mybb/mybb/pull/4376.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-22 12:31 UTC, Eldenroot commented
Thank you!

2021-05-25 21:24 UTC, euantorano requested changes
This looks good, just some minor comments.

2021-05-25 21:24 UTC, euantorano commented on install/resources/mybb_theme.xml
> +	var susp_pm = '{$suspm_check}';
Parent `<template>` tag needs `version="1827"`.

2021-05-25 21:24 UTC, euantorano commented on install/resources/mysql_db_tables.php
> +	pmsuspensiontime int unsigned NOT NULL default '0',
```suggestion
  pmsuspensiontime int unsigned NOT NULL default '0',
```

Minor change to indentation.

2021-05-26 20:44 UTC, Sama34 approved these changes

2021-05-26 20:44 UTC, Sama34 commented on modcp.php
> +	// Do we mark the suspend posts box?
```suggestion
	// Do we mark the suspend pms box?
```

2021-05-27 14:22 UTC, euantorano approved these changes

2021-11-20 21:57 UTC, Xazin commented
Should I close this?

2021-11-24 15:56 UTC, dvz commented
We'll be redirecting new features to 1.9, so it can be adjusted to target the `dev-1.9` branch instead.

From a brief look, `global.php` (where links to `private.php` and new message checks & alerts are produced) will also need to be modified.

We can also consider allowing access to the PM system to allow reading past messages, but disallowing sending new ones.

2025-10-27 18:29 UTC, Ben-MyBB commented
I'm not sure what we can do with this PR now, but I'd really like to see it in 1.9.

2025-10-28 11:55 UTC, arcalys commented
Maybe push the related issue here. If Xazin can retarget it to 1.9, great — otherwise, I can take over and continue it.

2025-11-09 02:52 UTC, Sama34 commented
@arcalys feel free to send a PR for 1.9, maybe based off this PR

@Xazin we appreciate your contribution !

Regards.

2025-11-09 02:52 UTC, closed without merging