Fix #4384 Soft deleted thread may be visible in User CP Home's subscr…
mybb/mybb pull request #4385
Opened 2021-06-10 18:05 UTC by Sama34

…iptions

Resolves #4384

2021-06-13 21:41 UTC, dvz requested changes

2021-06-13 21:41 UTC, dvz commented on usercp.php
> +
It is already initialized a few lines below in `feature` (https://github.com/mybb/mybb/commit/ed09961345ac1ed5f8d34774f995b4c430389602)

2021-06-13 21:42 UTC, dvz commented
This changes logic around the `visible` state. Should soft deleted and unapproved threads be displayed in _Your Latest Threads_ and subscriptions?

2021-06-15 14:01 UTC, dvz approved these changes

2021-06-15 14:01 UTC, merged

2021-06-15 17:01 UTC, Eldenroot commented
> This changes logic around the `visible` state. Should soft deleted and unapproved threads be displayed in _Your Latest Threads_ and subscriptions?

I think yes they should... but these should have different color to know that they are unapproved/deleted. And these should be visible only to the author, not for visitors.