Fixes #4492 - SCEditor returns unsupported mycode format...
mybb/mybb pull request #4493
Opened 2021-11-08 17:35 UTC by Eldenroot

Resolves #4492 

Fix by doylecc

2022-07-08 12:11 UTC, dvz requested changes

2022-07-08 12:11 UTC, dvz commented on inc/functions_posting.php
> +	if(empty($quoted_post['username']))
Indentation here seems incorrect

2022-07-08 16:22 UTC, dvz approved these changes

2022-07-23 16:46 UTC, merged

2023-06-24 14:42 UTC, PARADOXP reviewed
so what is the difference?