Security event logging
mybb/mybb pull request #4599
Opened 2022-11-09 22:39 UTC by Starpaul20

Starting work on #4577

2023-01-13 17:35 UTC, dvz commented
Tangentially related - some practical changes made to the Security Log plugin: https://github.com/Starpaul20/Security-Log/pull/3

2024-05-25 18:57 UTC, Sama34 requested changes

2024-05-25 18:57 UTC, Sama34 commented on usercp.php
> +	output_page(\MyBB\template('usercp/securitylog.twig', [
```suggestion
	output_page(\MyBB\View\template('usercp/securitylog.twig', [
```

2024-05-25 18:57 UTC, Sama34 commented on usercp.php
> +
```suggestion

    $multipage = $multipage ?? '';
    
```

2024-05-25 18:57 UTC, Sama34 commented on admin/modules/tools/securitylog.php
> +		if($mybb->input['uid'])
```suggestion
		if($mybb->get_input('uid') !== '')
```

2024-05-25 19:01 UTC, Sama34 approved these changes

2024-05-25 19:01 UTC, merged