Search results display with invalid sid
mybb/mybb pull request #4668
Opened 2023-03-02 19:40 UTC by Eldenroot

https://community.mybb.com/thread-237717.html

2023-03-03 16:45 UTC, Stefan-MyBB requested changes

2023-03-03 16:45 UTC, Stefan-MyBB commented on search.php
> +	if(isset($search['sid']) && !$search['sid'])
This looks wrong to me. I suggest `if(empty($search['sid']))`.

2023-03-03 16:45 UTC, Stefan-MyBB commented on search.php
> +	if(isset($search['keywords']))
`!empty` could be used here.

2023-03-10 18:40 UTC, Eldenroot commented
@Stefan-MyBB - thank you, it should be better now...

2023-04-30 18:33 UTC, merged