Full text search warnings
mybb/mybb pull request #4669
Opened 2023-03-02 19:44 UTC by Eldenroot

https://community.mybb.com/thread-237723.html

2023-03-03 16:48 UTC, Stefan-MyBB requested changes

2023-03-03 16:48 UTC, Stefan-MyBB commented on inc/functions_search.php
> +	if(isset($search['tid']) && $search['tid'])
I suggest using `if(!empty($search['tid']))` here.

2023-03-03 16:48 UTC, Stefan-MyBB commented on inc/functions_search.php
> +		if(isset($search['tid']) && !$search['tid'])
That looks wrong to me. I suggest using `!empty`.

2023-03-10 18:45 UTC, Eldenroot commented
@Stefan-MyBB - thank you, it should be fixed now

2023-04-30 18:31 UTC, dvz requested changes

2023-04-30 18:31 UTC, dvz commented on inc/functions_search.php
> +		if(!empty($search['tid']))
The logic got modified - `empty()` alone (rather than `!empty()`) would be appropriate in place of a `!` negation

2023-04-30 19:41 UTC, merged