Fixes #4748 - Increment "attachmentcount" in the "_threads" table
mybb/mybb pull request #4749
Opened 2023-09-10 12:40 UTC by Eldenroot

Resolves #4748

2023-09-12 20:35 UTC, Eldenroot commented
Typo fixed, srry :)

2023-10-05 17:13 UTC, dvz requested changes

2023-10-05 17:13 UTC, dvz commented on modcp.php
> -		");
The indentation for this section got mistakenly changed (see whitespace differences)

2023-10-17 18:39 UTC, Eldenroot commented on modcp.php
> -		");
You are right :(

2023-10-25 16:34 UTC, dvz requested changes

2023-10-25 16:34 UTC, dvz commented on modcp.php
> +	redirect("modcp.php?action=modqueue&type=attachments", $lang->redirect_attachmentsmoderated);
Accidental indentation changes

2023-10-28 18:56 UTC, Eldenroot commented on modcp.php
> +	redirect("modcp.php?action=modqueue&type=attachments", $lang->redirect_attachmentsmoderated);
@dvz - Idk, I see something different than Github? Maybe some sync refresh issue?

2023-10-29 14:55 UTC, merged